
CREATE MASTER KEY
GO

CREATE SCHEMA ext
GO


CREATE DATABASE SCOPED CREDENTIAL ADLS_GEN2_USER_MSI
WITH IDENTITY = 'Managed Service Identity'
GO


CREATE EXTERNAL DATA SOURCE pbDemoDS
WITH
(
	TYPE = HADOOP,
	LOCATION = 'abfss://<container@storageaccountname>.dfs.core.windows.net',
	CREDENTIAL = ADLS_GEN2_USER_MSI
);
GO

CREATE EXTERNAL FILE FORMAT pbDemoDF
WITH
(
	FORMAT_TYPE = DELIMITEDTEXT,
	FORMAT_OPTIONS (
		FIELD_TERMINATOR = ',',
		STRING_DELIMITER = '',
		DATE_FORMAT = 'MM/dd/yyyy',
		USE_TYPE_DEFAULT = False
	)
);
GO
